apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-dvfi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-dvfi@sha256:efe5ef007e828cf515de7d7405ca212435133dd5074a615d7976827e24e3fbfe
        name: my-nodejs
        resources: {}
status: {}
